name: PHP 8.0
on: [push]
jobs:
  composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer install
        uses: php-actions/composer@v6
        with:
          php_version: "8.0"

      - name: Archive build
        run: mkdir /tmp/github-actions/ && tar -cvf /tmp/github-actions/build.tar ./

      - name: Upload build archive for test runners
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: /tmp/github-actions

  phpunit:
    runs-on: ubuntu-latest
    needs: [ composer ]

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: /tmp/github-actions

      - name: Extract build archive
        run: tar -xvf /tmp/github-actions/build.tar ./

      - name: PHP Unit tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: cover
        with:
          version: "9.5"
          php_version: "8.0"
          php_extensions: xdebug
          configuration: phpunit.xml
          bootstrap: vendor/autoload.php
          coverage_text: _coverage/coverage.txt
          coverage_clover: _coverage/clover.xml

  phpstan:
    runs-on: ubuntu-latest
    needs: [ composer ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: /tmp/github-actions

      - name: Extract build archive
        run: tar -xvf /tmp/github-actions/build.tar ./

      - name: PHP Static Analysis
        uses: php-actions/phpstan@v3
        with:
          php_version: "8.0"
          path: src/

  phpmd:
    runs-on: ubuntu-latest
    needs: [ composer ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: /tmp/github-actions

      - name: Extract build archive
        run: tar -xvf /tmp/github-actions/build.tar ./

      - name: PHP Mess Detector
        uses: php-actions/phpmd@v1
        with:
          php_version: "8.0"
          path: src/
          output: text
          ruleset: phpmd.xml

  phpcs:
    runs-on: ubuntu-latest
    needs: [ composer ]

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: /tmp/github-actions

      - name: Extract build archive
        run: tar -xvf /tmp/github-actions/build.tar ./

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: "8.0"
          path: src/
          standard: phpcs.xml

  remove_old_artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Remove old artifacts for prior workflow runs on this repository
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api "/repos/${{ github.repository }}/actions/artifacts?name=build-artifact" | jq ".artifacts[] | select(.name == \"build-artifact\") | .id" > artifact-id-list.txt
          while read id
          do
            echo -n "Deleting artifact ID $id ... "
            gh api --method DELETE /repos/${{ github.repository }}/actions/artifacts/$id && echo "Done"
          done <artifact-id-list.txt